### ISSUE TITLE
denseDepthMap output problem

### ISSUE THREAD

**Issue by mouawiya** [Andyyyyyyyyyyyy/LiDAR-Sparse-Projection-Map-Interpolation#1]
hi, i've tried your code of denseDepthMap and i was facing some problem with the output results, i was having pictures like these which are not the ones you published with the work, Note: i didn't change anything in the code
![000000](https://user-images.githubusercontent.com/89226952/130152967-94534701-1c60-4dae-af7a-be8d36c7638c.jpg)
![000008](https://user-images.githubusercontent.com/89226952/130152979-91985e44-a22a-49a5-83e0-4d358154c891.jpg)

**Comment by Andyyyyyyyyyyyy** [comment]
> hi, i've tried your code of denseDepthMap and i was facing some problem with the output results, i was having pictures like these which are not the ones you published with the work, Note: i didn't change anything in the code
> ![000000](https://user-images.githubusercontent.com/89226952/130152967-94534701-1c60-4dae-af7a-be8d36c7638c.jpg)
> ![000008](https://user-images.githubusercontent.com/89226952/130152979-91985e44-a22a-49a5-83e0-4d358154c891.jpg)

I have revised the code DDM.py, you can try it again.

**Comment by mouawiya** [comment]
thank you, i've tried it, and it works fine now thank you
